import { getRandomInt } from './utils.js'

const complimentData = [
  'Excellent work!',
  'Wonderful work!',
  'You are very good at this.',
  'This was first class work.',
  'This is a real work of art.',
  'Good work!',
  'This is the best ever.',
  'Superb work!',
  'Exactly right!',
  'You did this very well.',
  'You’ve just about got it.',
  'You are doing a good job!',
  'This is better than ever.',
  'You certainly did well today.',
  'Keep it up!',
  'Now you’ve figured it out.',
  'Fine work!',
  'Outstanding work!',
  'Great job!',
  'You’re really improving.',
  'I knew you could do it.',
  'Fantastic work!',
  'You are learning a lot.',
  'Congratulations!',
  'Tremendous work!',
  'I’m impressed.',
  'Keep working on it; you’re improving.',
  'Congratulations, you got it right!',
  'You must have been practicing.',
  'You did a lot of work today.',
  'You are learning fast.',
  'Marvelous work!',
  'I like this.',
  'Couldn’t have done it better myself.',
  'Now This is what I call a fine job.',
  'You’ve just about mastered this.',
  'You’ve got the hang of it!',
  'I’ve never seen anyone do it better.',
  'You’re getting better and better.',
  'It looks like you’ve put a lot of work into this.',
  'You’re on the right track now.',
  'Keep on trying!',
  'This is really nice.',
  'What neat work!',
  'Keep up the good work.',
  'You make it look easy.',
  'Terrific job!',
  'Superior work.',
  'This is the way to do it.',
  'I knew you could do it.',
]

// must be a function instead of a variable to get random num
export const getRandomCompliment = () =>
  complimentData[getRandomInt(complimentData.length)]
